const express = require("express")

const adminRoute = require("./admin.routes")
const bookRoute = require("./book.routes")
const chachaRoute = require("./chacha.routes")
const productRoute = require("./product.routes")
const blogRoute = require("./blog.routes")
const contactRoute = require("./contact.routes")
const studentRoute = require("./student.routes")
const eventRoute = require("./event.routes")
const recipeRoute = require("./recipe.routes")
const zooRoute = require("./zoo.routes")
const furnitureRoute = require("./furniture.routes")
const treeRoute = require("./tree.routes")
const musicRoute = require("./music.routes")
const toyRoute = require("./toy.routes")
const riverRoute = require("./river.routes")

const router = express.Router()

router.use("/admin",adminRoute)
router.use("/book",bookRoute)
router.use("/chacha",chachaRoute)
router.use("/product",productRoute)
router.use("/blog",blogRoute)
router.use("/contact",contactRoute)
router.use("/student",studentRoute)
router.use("/event",eventRoute)
router.use("/recipe",recipeRoute)
router.use("/zoo",zooRoute)
router.use("/furniture",furnitureRoute)
router.use("/tree",treeRoute)
router.use("/music",musicRoute)
router.use("/toy",toyRoute)
router.use("/river",riverRoute)

module.exports = router